/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyContract } from "./MyContract";
export type { Notary } from "./Notary";
export * as factories from "./factories";
export { MyContract__factory } from "./factories/MyContract__factory";
export { Notary__factory } from "./factories/Notary__factory";
