/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Notary {
  export type RecordStruct = {
    notarizer: AddressLike;
    timestamp: BigNumberish;
    filename: string;
    label: string;
  };

  export type RecordStructOutput = [
    notarizer: string,
    timestamp: bigint,
    filename: string,
    label: string
  ] & { notarizer: string; timestamp: bigint; filename: string; label: string };
}

export interface NotaryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAll"
      | "getByOwner"
      | "getRecord"
      | "notarize"
      | "totalCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Notarized"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAll",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getRecord", values: [string]): string;
  encodeFunctionData(
    functionFragment: "notarize",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getByOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "notarize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalCount", data: BytesLike): Result;
}

export namespace NotarizedEvent {
  export type InputTuple = [
    notarizer: AddressLike,
    rootHash: string,
    filename: string,
    label: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    notarizer: string,
    rootHash: string,
    filename: string,
    label: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    notarizer: string;
    rootHash: string;
    filename: string;
    label: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Notary extends BaseContract {
  connect(runner?: ContractRunner | null): Notary;
  waitForDeployment(): Promise<this>;

  interface: NotaryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAll: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getByOwner: TypedContractMethod<[addr: AddressLike], [string[]], "view">;

  getRecord: TypedContractMethod<
    [rootHash: string],
    [Notary.RecordStructOutput],
    "view"
  >;

  notarize: TypedContractMethod<
    [rootHash: string, filename: string, label: string],
    [void],
    "nonpayable"
  >;

  totalCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAll"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getByOwner"
  ): TypedContractMethod<[addr: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [rootHash: string],
    [Notary.RecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "notarize"
  ): TypedContractMethod<
    [rootHash: string, filename: string, label: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Notarized"
  ): TypedContractEvent<
    NotarizedEvent.InputTuple,
    NotarizedEvent.OutputTuple,
    NotarizedEvent.OutputObject
  >;

  filters: {
    "Notarized(address,string,string,string,uint256)": TypedContractEvent<
      NotarizedEvent.InputTuple,
      NotarizedEvent.OutputTuple,
      NotarizedEvent.OutputObject
    >;
    Notarized: TypedContractEvent<
      NotarizedEvent.InputTuple,
      NotarizedEvent.OutputTuple,
      NotarizedEvent.OutputObject
    >;
  };
}
