/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyContract__factory } from "./MyContract__factory";
export { Notary__factory } from "./Notary__factory";
